name: Build and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Archive WAR file
        uses: actions/upload-artifact@v2
        with:
          name: application-war
          path: build/libs/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: application-war
          path: ./build/libs

      - name: Create SSH key file
        env:
          SCP_KEY: ${{ secrets.SCP_KEY }}
        run: |
          echo "${{ env.SCP_KEY }}" > scp_key.pem
          chmod 600 scp_key.pem

      - name: Verify SSH key file
        run: ls -la scp_key.pem

      - name: Copy WAR to EC2
        env:
          SCP_USER: ${{ secrets.SCP_USER }}
          SCP_HOST: ${{ secrets.SCP_HOST }}
          SCP_PATH: ${{ secrets.SCP_PATH }}
        run: |
          scp -v -o StrictHostKeyChecking=no -i scp_key.pem ./build/libs/*.war $SCP_USER@$SCP_HOST:$SCP_PATH/ROOT.war

      - name: Deploy to Tomcat on EC2
        env:
          SSH_KEY: ${{ secrets.SCP_KEY }}
          SSH_USER: ${{ secrets.SCP_USER }}
          SSH_HOST: ${{ secrets.SCP_HOST }}
          SCP_PATH: ${{ secrets.SCP_PATH }}
        run: |
          echo "${{ env.SSH_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $SSH_USER@$SSH_HOST << EOF
            cd $SCP_PATH
            sudo chmod +x ./stop.sh
            sudo chmod +x ./deploy.sh
            ./stop.sh
            ./deploy.sh
          EOF
